FROM centos

# Install Development packages and Java tools
# -------------------------------------------
RUN yum groupinstall 'Development Tools' -y &&\
    yum install java-1.8.0-openjdk-devel git -y &&\
    yum update -y && yum clean all

# Define users and groups
# -----------------------
RUN groupadd -g 501 devgroup &&\
    adduser -m -d /home/devuser -s /bin/bash -u 500 -g devgroup devuser

# Install runtime packages needed
# -------------------------------
RUN yum install -y binutils.x86_64 compat-libcap1.x86_64 gcc.x86_64 \
			gcc-c++.x86_64 \
            glibc.i686 glibc.x86_64 glibc-devel.i686 \
            glibc-devel.x86_64 ksh compat-libstdc++-33 \
            libaio.i686 libaio.x86_64 libaio-devel.i686 libaio-devel.x86_64 \
            libgcc.i686 \
            libgcc.x86_64 libstdc++.i686 libstdc++.x86_64 \
            libstdc++-devel.i686 libstdc++-devel.x86_64 \
			sysstat.x86_64 zip unzip
RUN yum install -y httpd
ENTRYPOINT [ "top", "-b" ]
CMD [ "sh", "-c", "cat" ]